server:
  servlet:
    context-path: /report
  port: 11101
spring:
  datasource:
    url: jdbc:mysql://34.92.159.177:3306/estate_report?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&autoReconnect=true
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
